### PR TITLE
Implement slot logic, improve tests.

### PR DESCRIPTION
**Pull request by sjlongland**
This adds a new class, `signalslot.Slot`, which is a callable class for wrapping methods and functions.  Crucially, the `Slot` class supports weak binding, falling back to doing a no-op when the binding breaks.

The `Signal` class supports testing for whether a binding is valid and automatically drops references to "dead" slots.

I've also done some tweaks to the .coveragerc configuration to prevent it testing the coverage of tests, and tweaked the tests for the `signalslot.contrib.Test` class so that most of the branches are tested.

### CODE REVIEW

**Comment by davethecipo** [comment]
Hi,

I think that it would be better if you opened a pull request to the official [repository](https://github.com/Numergy/signalslot) of signalslot, I don't even have the technical knowledge to understand what you did

**Comment by sjlongland** [comment]
Ahh okay, I must've mistook this one for the master.  No worries, I'll rebase my commits and see what happens.

**Comment by davethecipo** [comment]
Thanks! I still found your PR useful, I discovered what weak references are ;-)

**Comment by sjlongland** [comment]
On 23/04/15 04:59, Davide Olianas wrote:
> Thanks! I still found your PR useful, I discovered what weak references
> are ;-)

Indeed, I've actually learned a lot about PEP8 compliance in fixing the
errors that appear in the test suite and about unit tests in general.
(This is something I've always chucked in the "too hard" basket.)

I'm a self-taught programmer who has learned by doing.  Weak references
is one trick that I found I needed to learn due to past wrestling
matches with the garbage collector; figuring out how to weakly reference
an object's method was another trick I did for fysom.

I did my own function that wrapped a callable as a reference, then
discovered someone had backported Python 3.4's weakref.WeakMethod to
Python 2.6-3.3 in the 'weakrefmethod' module.  Live and learn it seems.

If the commits have been educational, then it's been worthwhile. :-)
-- 
Stuart Longland (aka Redhatter, VK4MSL)

I haven't lost my mind...
  ...it's backed up on a tape somewhere.

**Pull request closed without merging**
